### ISSUE TITLE
Calculate dark / light colors shades from the inverted color

### ISSUE THREAD

**Issue by mateusleon** [onury/invert-color#11]
It's possible to setup some inference over the calculated inverted color to use its corresponding black and white shade, like it was converted from rgb to black and white in any sort of image editing program?

I was wondering that in cases where we want to calculate de inverted color but are not able to inform the proper shade of dark / light color that can combine well with the original color.

**Comment by onury** [comment]
This library implements "invert" function which is quite different. I think what you refer to is called "desaturate" or "grayscale". (Though, I have plans to implement these and more in separate packages).

**Comment by onury** [comment]
As mentioned, this feature is for another (micro) library.
Closing this now. Re-open if needed.

**Comment by mateusleon** [comment]
Actually, I'm thinking with the "invert" perspective too. I'll try to explain (English is not my mother language).

Sometimes, from a design perspective, using plain black / white over some color is not pleasant, and I think that was the reason to implement the dark / light options, to provide a more reasonable shade to be used.

However, in some cases when you aren't able to know the proper dark / light shades to be used, simply because you're dealing with a system were the user can input colors to create a theme, the fixed nature of these properties can be a problem.

For this reason I was wondering if the "invert" function can work with it's inversion normally, but, when it'll calculate the luminance, despite selecting from a dark / light shade, it'll "desaturate" or "grayscale" the inverted color, in order to give a "no tinted" shade of itself.

Here's a pen illustrating this scenario: https://codepen.io/mateusleon/pen/geVQVj
