### ISSUE TITLE
Option to custom adjust when color is flipped between black or white

### ISSUE THREAD

**Issue by bytewiz** [onury/invert-color#15]
Is it currently possible to adjust when a given color will flip to black or white when e.g. doing:

```javascript 
invert('#f46e76', true) // produces black and want to produce white
```

**Comment by onury** [comment]
No, sorry. That's against "invert"ing.. :)

**Comment by bytewiz** [comment]
@onury alright, thanks for the quick reply!

**Comment by onury** [comment]
BTW, it's still against "inverting" but you could hack around it like:
```js
invert('#f46e76', { black: '#fff', white: '#000' })
```
🤔
