### ISSUE TITLE
Is it possible to customize the contrast threshold?

### ISSUE THREAD

**Issue by marcodevsquad** [onury/invert-color#16]
In bootstrap 4 we have a variable called `$yiq-contrasted-threshold:` were has a value of 150 by default and this variable ajusts the threshold to decide if the color should be black or white in components. Is there something similar to this?

I thought something like this:

```javascript
invert('#d9534f', { threshold: 155 }); // #ffffff
```

And congrats for this awesome project! Thank you very much!

**Comment by onury** [comment]
Thanks.

The default threshold of this library is gathered from the formula given for contrast in the [W3C Recommendations](http://www.w3.org/TR/WCAG20/). There is an inner constant for [luminance threshold](https://github.com/onury/invert-color/blob/master/src/invert.ts#L38) but currently there is no option to customize this with exposed API. 

The threshold value is in a scale of `0.0` (lowest) to `1.0` (highest). The default threshold is calculated with `Math.sqrt(1.05 * 0.05) - 0.05` which is approx. `~0.179`. I don't know the scale of that bootstrap variable. You would need to convert it to `0.0-1.0` scale or vice-versa.

I'll mark this to be implemented.

**Comment by onury** [comment]
Notes for implementation:
- Add optional property `threshold?: number` to `BlackWhite` interface.
- Expose default threshold calculated value as `defaultThreshold` property. Remove `BW_THRESHOLD` constant.
- Update related methods.

**Comment by marcodevsquad** [comment]
Thank you for your fast reply! Just to complement, this feature IMHO will make your package **perfect** and **complete**!

Congratulations for this project!! Keep on moving! 😉 👍

**Comment by onury** [comment]
Added this in [v2.0.0](https://github.com/onury/invert-color#v200-2018-11-09) (unreleased).
Hope this works for you.
I'll release as soon as #17 fix is confirmed.

**Comment by onury** [comment]
released.
