### ISSUE TITLE
Types incorrect or problem with webpack.

### ISSUE THREAD

**Issue by ozyman42** [onury/invert-color#17]
`invert` is not a function. This happens no matter how I import:
`import invert from "invert-color"` -> Runtime error: `invert_color_1.default is not a function`
`import { invert } from "invert-color"` -> Runtime error: `invert_color_1.invert is not a function`
`import * as invert from "invert-color"` -> Compiletime error: `Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("D:/.../node_modules/invert-color/lib/invert")' has no compatible call signatures.`
`import invert = require("invert-color")` -> Compiletime error: `Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("D:/.../node_modules/invert-color/lib/invert")' has no compatible call signatures.`

for it only works when use as  `(invert as any)(rgbArray)` and I either import as
`import * as invert from 'invert-color'`
or
`import invert = require('invert-color')`

I'm using this with webpack in the browser.

**Comment by onury** [comment]
Thanks. It's strange that no one has reported this before.

Can you [clone](https://github.com/onury/invert-color.git) v2.0.0 and try with:
```js
import invert from 'invert-color';
```
See [updated readme](https://github.com/onury/invert-color#usage).
I've removed dual export, now only using default export.
Built with rollup for [UMD, CJS, ESM, etc](https://github.com/onury/invert-color/tree/master/lib)..

Once you confirm, I'll release [v2.0.0](https://github.com/onury/invert-color#v200-2018-11-09)

**Comment by ozyman42** [comment]
I uninstalled the 1.5.0 version then installed the new one via
`npm i --save https://github.com/onury/invert-color/tarball/master`

After changing the code to `import invert from 'invert-color';` as you instructed, I'm still getting no compile-time error, but getting the same runtime error of `invert_color_1.default is not a function`.

I am using the repository https://github.com/mobxjs/mobx-react-typescript-boilerplate as a base so perhaps something about the configuration of that repo isn't as it should be.

**Comment by onury** [comment]
That's strange. I don't know about that repo but simple babel tests work ok.
It actually works for both versions `1.5.0` and `2.0.0`.

Try this test for example: [invert-test.zip](https://github.com/onury/invert-color/files/2569434/invert-test.zip)


### package.json
```json
{
  "name": "invert-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "compile": "npx babel index.js --out-file index-compiled.js --sourceType module --presets=@babel/preset-env",
    "test": "npm run compile && node index-compiled.js"
  },
  "license": "ISC",
  "dependencies": {
    "invert-color": "onury/invert-color"
  },
  "devDependencies": {
    "@babel/cli": "^7.1.5",
    "@babel/core": "^7.1.5",
    "@babel/preset-env": "^7.1.5"
  }
}
```
### index.js
```js
import invert from 'invert-color';
console.log(invert('#000'), '—» works!');
```
then run `npm i && npm test`

So I think the issue is with your project or configurations..

**Comment by onury** [comment]
Closing this now. 
But I'd like to know what's causing your issue...

**Comment by AlexLeung** [comment]
I think that this module isn't compatible with webpack+typescript. I updated the webpack versions of my repo (from 3 to 4) and switched from "awesome-ts-loader" to the standard "ts-loader", but I'm still getting the same issue.

**Comment by ozyman42** [comment]
Okay I figured it out. If using typescript, users need to have a tsconfig.json option of `"esModuleInterop":true` or they get the error I described.
