### ISSUE TITLE
Feature proposal: pass dark/light color codes for bw option

### ISSUE THREAD

**Issue by BrainCrumbz** [onury/invert-color#2]
Hi there

currently in a project we're using a combination of [color-convert](https://www.npmjs.com/package/color-convert) plus custom code to decide if a color is "bright" or dark, so to apply an opposite custom dark/light text color.  
Our dark/light text colors are not pure `#000`/`#FFF`, but somehow closer.

Would you consider a different API like e.g. the following, here expressed as TypeScript just for clarity:

```ts
invert(colorCode: string, bw: boolean | BwColorCodes);

interface BwColorCodes {
  dark: string;
  light: string;
}
```

So all in all you could invoke `invertColor(colorCode, true)` to get current B/W behavior, or you could also call:

```ts
invertColor(colorCode, {
  dark: myCustomDarkColor,
  light: myCustomLightColor,
});
```

In case, what would be the other API that needs change? Would you consider a PR targeting this?

Thanks

**Comment by onury** [comment]
Sure. Just send a PR.
Support should be added for all methods that has a `bw` option in this case, such as:
- `~invertToBW()` » this is an internal (private) method used by all others. This is the only part where black and white hex colors are defined, so you'd need to implement a third argument here.
- `invert()`
- `invert.asRgbArray()`
- `invert.asRgbObject()`

Note: Maybe for semantics, we should refactor `bw` to `amplify` and `invertToBW` to `invertAmplify`...

Also pls add tests for this.

**Comment by BrainCrumbz** [comment]
Thanks for feedback, cool. Sure there'll be tests as well, that would be the first step.

About semantics, don't know. *Black & white* as a terminology was quite easy to grasp, almost without reading docs at all. *Amplify* does not seem so easy to catch at first. Anyhow, just our 2¢.

Let us first try with this PR. After that goes in, if you feel like changing API names, at that point I'd suggest adding new APIs altogether, and making the old ones somehow deprecated (e.g. with a `console.warn`, not sure how else). Just not to cause breaking changes.

**Comment by BrainCrumbz** [comment]
~~BTW, still about naming: maybe instead of *dark* Vs *light*, we should go for *dark* Vs *bright*, which English-wise seems more appropriate.~~ Forget about that: usually colors are named as *dark green* Vs *light green*, so that's ok.

**Comment by onury** [comment]
> About semantics, don't know. Black & white as a terminology was quite easy to grasp, almost without reading docs at all. Amplify does not seem so easy to catch at first. Anyhow, just our 2¢.

Fair enough. Let's leave it `bw` but then again, the object properties should be `{ black, white }` for consistency (i.e. custom black/white).

> Let us first try with this PR. After that goes in, if you feel like changing API names, at that point I'd suggest adding new APIs altogether, and making the old ones somehow deprecated (e.g. with a console.warn, not sure how else). Just not to cause breaking changes.

This is a very small lib. We shouldn't break anything or log deprecation warnings. All public method signatures will be backwards compatible anyway. The one I suggested was an internal method (`invertToBW()`) which will not be refactored in this case. 

So pls just rename the props to black/white instead of dark/light.

I can either accept this PR as is now and wait for a second one before releasing. Or you can make the final changes and re-submit.

cheers.

**Comment by BrainCrumbz** [comment]
> So pls just rename the props to black/white instead of dark/light.

Now it should be ok.

Not sure what other changes you meant, though. Could you please explain that again?

**Comment by onury** [comment]
No other changes needed. I may revise the README later though. Thanks.
