### ISSUE TITLE
Chore: clean up published package directory

### ISSUE THREAD

**Issue by BrainCrumbz** [onury/invert-color#4]
Looking at package contents when installed from client code, there are more files than needed. That makes package larger and less clear to reason about.

It'd be nice to achieve a package directory listing like:

```sh
index.js
LICENSE
package.json
README.md
```

If you're ok with that, we already have a working PR.

Apart from changes from that PR, one important bit is that the package file to be published should be generated by running `npm pack` (instead of zipping the whole directory content, or some similar procedure).

What's your take about it? Thanks

**Comment by onury** [comment]
What do you mean by "installed from client code"? This should be installed via npm and package.json has [`files` setting](https://github.com/onury/invert-color/blob/master/package.json#L13) which is all needed.

**Comment by BrainCrumbz** [comment]
Sorry, *client code* <=> *client project*, the one taking this package as a dependency. This is what we find in `node_modules\invert-color` after running `npm install` in client project:

```sh
              249 .editorconfig     
              550 .eslintrc.json    
               11 .gitattributes    
              100 .npmignore        
            1.890 index.js          
            1.121 LICENSE           
            2.517 package.json      
            1.905 README.md         
   <DIR>          test              
              506 todo.md           
```

For some reason, it seems like package downloaded from npm was not created by `npm pack`. And yes, `files` property in `package.json` was correctly set already, we did not touched that.

In case you may want to have a look, the changes we're suggesting can be compared [here](https://github.com/BrainCrumbz/invert-color/compare/master...chore/dont-ship-anim).  
As a matter of fact, in the end there was nothing to change in `package.json`, but still it seemed odd to have `anim` folder within tests, as GIF is only used in docs, that's why we moved those under `docs`.  
Then we found that some paths were being inadvertedly ignored in Git, so we brought in a standard Node.js *.gitignore* file.

**Comment by onury** [comment]
I see. That's because `files` setting is [added after](https://github.com/onury/invert-color/commit/8b8e8b010a45ffe3f9ee95a217673a5a177e985d) the initial version.

So no need for additional actions. 
Once the new version is released, it's already resolved.

**Comment by onury** [comment]
v1.1.0 is released. Thanks for the input.
