### ISSUE TITLE
Feature proposal: consider exporting hexToRGB or other utility functions

### ISSUE THREAD

**Issue by BrainCrumbz** [onury/invert-color#5]
Looking at source code, this library defines a `hexToRGB` function which might be useful to client code when working with colors. The idea would be to export this function, and maybe some other if it makes sense, without exposing all library implementation details. So that one can avoid copying code, or importing another library, just for that. Of course, this library should stay focused and not become a catch-all color utility. This suggestion is just because that function *happens* to be there already.

Just our 2¢. What do you think?  
Regards

**Comment by onury** [comment]
I typically follow "Single Responsibility Principle" when releasing OSS. But determining/defining what the responsibility should be; is the crucial part.

HEX to RGB is ok but typically users will also need to convert from RGB to HEX.
If they're using this for CSS, HSL conversion could be added too.
So `hexToRGB` will not be a standalone module, but instead a color conversion utility would suit better.

I got half a project for this (JS) and some other code needs to be ported from a Python project of mine. If and once this gets released, any contribution is welcome for that too 😎 

cheers.

**Comment by BrainCrumbz** [comment]
That's ok, it makes sense.

Before investing more time in color utilities, you might want to have a look at other existing color conversion libraries around, like [color-convert](https://github.com/Qix-/color-convert). Maybe your needs would be already fulfilled, or you might contribute to that.

Going to close this issue now. Cheers

**Comment by onury** [comment]
Yep, just don't like the API as much. Thanks.
