### ISSUE TITLE
Request for better error message(s)

### ISSUE THREAD

**Issue by CAYdenberg** [onury/invert-color#8]
If you pass an invalid color into invert you get

```js
Uncaught TypeError: Cannot read property 'r' of null
```

which is hard to interpret, and doesn't give you much clue that the error is occurring in this package.

I'd be happy to contribute a PR if you're likely to merge it.

**Comment by onury** [comment]
You're very welcome to send a PR. 

If you ask me; the only line with a `.r` is within [`toRGB()` method](https://github.com/onury/invert-color/blob/master/src/index.js#L36). I'd validate the `c` argument and throw `"Invalid color value."`

**Comment by onury** [comment]
v1.2.3 is released.
